version: 2
updates:
  - package-ecosystem: "gradle"
    open-pull-requests-limit: 2
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "woocommerce/android-developers"
    ignore:
      - dependency-name: "com.android.tools.build:gradle"
