version: 2
updates:
  - package-ecosystem: "gradle"
    open-pull-requests-limit: 5
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "woocommerce/android-developers"
      - "woocommerce/platform-9"
    ignore:
      - dependency-name: "com.android.tools.build:gradle"
