language: android
jdk: oraclejdk8
sudo: required

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
    - extra-android-m2repository
    - extra-android-support
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27

env:
  global:
    - MALLOC_ARENA_MAX=2
    - GRADLE_OPTS="-Xmx768m -Xms256m -Xss1m"
    - ANDROID_SDKS=android-21
    - ANDROID_TARGET=android-21

install:
  # Setup gradle.properties
  - cp gradle.properties-example gradle.properties

script:
  - ./gradlew assembleVanillaRelease --stacktrace
  - ./gradlew testVanillaRelease --stacktrace
  - ./gradlew lintVanillaRelease --stacktrace || (grep -A20 -B2 'severity="Error"' */build/**/*.xml; exit 1)
  - ./gradlew checkstyle --stacktrace
  - ./gradlew ktlint --stacktrace
  - bundle install
  - bundle exec danger
