language: android
jdk: oraclejdk8

android:
  components:
    - extra-android-m2repository
    - extra-android-support
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27

env:
  global:
    - MALLOC_ARENA_MAX=2
    - GRADLE_OPTS="-Xmx768m -Xms256m -Xss1m"
    - ANDROID_SDKS=android-17
    - ANDROID_TARGET=android-17

install:
  # Setup gradle.properties
  - cp gradle.properties-example gradle.properties

script:
  - ./gradlew assembleVanillaRelease
  - ./gradlew testVanillaRelease
  - ./gradlew lintVanillaRelease || (grep -A20 -B2 'severity="Error"' */build/**/*.xml; exit 1)
  - ./gradlew checkstyle
  - ./gradlew ktlint
